apiVersion: v1
kind: Service
metadata:
  name: backend-service # name of the service
spec:
  type: LoadBalancer # Externalyl accessible
  ports:
  - name: http
    port: 8000 # Port exposed externally
    targetPort: 8000 #Container port
  selector:
    app: backend