apiVersion: v1
kind: Secret #Resource type - secret
metadata:
  name: frontend-secret #secret name
type: Opaque # Generic secret type
data:
  # Encoded "http://127.0.0.1:8000"
  BACKEND_URL: "aHR0cDovLzEyNy4wLjAuMTo4MDAw"