apiVersion: v1
kind: Service
metadata:
  name: frontend-service # service name
spec:
  type: LoadBalancer #externally accessible service
  ports:
  - name: http # name of the port
    port: 5000 # port exposed externally (accessible outside cluster)
    targetPort: 5000 # container port where container listens
  selector:
    app: frontend #route traffic to pods with this label